export const SET_TRIP_FINANCIALS = "SET_TRIP_FINANCIALS";
export const SET_PAYMENTS = "SET_PAYMENTS";
export const SET_MISC_EXPENSES = "SET_MISC_EXPENSES";
export const SET_CONCURRENCY_COSTS = "SET_CONCURRENCY_COSTS";
